### ISSUE TITLE
Добавление макроса Localizable Macro

### ISSUE THREAD

**Issue by AMiracle-creator** [nktssk/SwiftLombok#10]
Привет! Предлагаю добавить макрос локализации! Текущей реализации не хватает механизма для автоматизации процесса локализации в программном обеспечении.

Макрос Localizable Macro будет получать ключи перечисления из файла локализации и создавать переменные и методы, которые можно использовать для доступа к этим элементам. Это облегчит разработку, поскольку программа не должна постоянно ссылаться на файл локализации, чтобы получить доступ к переводам. Вместо этого, она будет использовать методы и переменные, созданные макросом.

**Comment by rishatl** [comment]
От меня ок ✅

**Comment by AMiracle-creator** [comment]
Открыл пр, проверяйте)
